장바구니 기능 구현
wecode-bootcamp-korea/22-1st-Villy-backend pull request #11
Opened 2021-07-12 04:50 UTC by Jacesoul

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 장바구니 보기, 추가, 삭제 수정 기능 구현 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- POST 메소드를 통해 장바구니 추가 
- GET 메소드를 통해 장바구니 보기(유저의 포인트도 함께)
- PATCH 메소드를 통해 상품 수량 변경 
- DELETE 메소드를 통해 장바구니 상제(부분삭제기능 포함)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-12 06:48 UTC, kst6294 reviewed
수정사항 확인해주시고, 통신 결과도 같이 올려주세요.
한 PR 에는 해당하는 기능에 대해서만 변경이력이 남을 수 있도록 해주세요!

2021-07-12 06:48 UTC, kst6294 commented on carts/views.py
> +            Cart.objects.create(user_id=user.id, product_id=product.id)
1 - 장바구니에 이미 있는 상품을 다시 추가하면 어떻게 되나요?
2 - product_id 를 전혀 보내지 않는 경우에 어떻게 되나요?

2021-07-12 06:48 UTC, kst6294 commented on carts/views.py
> +            if Cart.objects.filter(product_id=product, user_id=user).exists():
이 view 는 장바구니 페이지에서 그 안의 수량을 변경할 때문 사용하겠군요. 
그리고 보통 장바구니기능에서는 (장바구니 페이지에서가 아니라) 메인 페이지 등에서 장바구니에 상품 추가 하는 요청을 할 때, 이미 장바구니에 해당하는 품목이 있을 경우, 수량을 업데이트 하게 됩니다. 
이러한 관점에서 patch 와 post 에 해당하는 view 도 구분해주시면 좋겠습니다.

2021-07-12 06:48 UTC, kst6294 commented on carts/views.py
> +    def delete(self, request):
delete 에서는 body 를 사용하지 않는 방법을 고민해주세요.

2021-07-12 12:27 UTC, Jacesoul commented on carts/views.py
> +            Cart.objects.create(user_id=user.id, product_id=product.id)
1. exists()메소드를 통해 장바구니에 이미 있는 상품 걸러냈습니다.
2.  product_id 를 전혀 보내지 않는 경우는 value에러가 뜹니다.

2021-07-12 13:25 UTC, Jacesoul commented on carts/views.py
> +    def delete(self, request):
delete 기능을 path parameter로 구현해보았습니다. 만약 전체삭제 또는 부분삭제를 구현한다면 body를 통해 정보를 받아오는것이 맞을까요?

2021-07-12 13:31 UTC, Jacesoul commented on carts/views.py
> +            if Cart.objects.filter(product_id=product, user_id=user).exists():
처음 기획단계에서 이미 해당 상품이 장바구니에 담겨있는 상태에서 다시 메인페이지의 장바구니 추가버튼을 누르면 이미 장바구니에 담겨있는 상품이라는 창이 뜨게 됩니다.  
만약 순태님께서 말씀하신대로 변경을 해보고자 생각했을때 원래 장바구니 버튼은 post 메소드를 통해서 장바구니에 추가가 되게 하고 다음번부터는 조건문을 통해 이미 장바구니에 존재하는 상품은 수량이 올라가게끔 로직을 짤수 있을것 같습니다. 
post, patch에 해당하는 view 구분을 좀더 설명해주실수 있으신가요?

2021-07-12 14:05 UTC, Jacesoul commented
<img width="1016" alt="스크린샷 2021-07-12 오후 11 04 12" src="https://user-images.githubusercontent.com/75877363/125300960-7b041800-e365-11eb-8942-4cb73d2c626e.png">
<img width="1037" alt="스크린샷 2021-07-12 오후 11 04 35" src="https://user-images.githubusercontent.com/75877363/125301013-88b99d80-e365-11eb-9175-d13002cea5b1.png">
<img width="1057" alt="스크린샷 2021-07-12 오후 11 05 01" src="https://user-images.githubusercontent.com/75877363/125301093-9a02aa00-e365-11eb-8aa0-aaba5bdf6938.png">
<img width="1067" alt="스크린샷 2021-07-12 오후 11 05 27" src="https://user-images.githubusercontent.com/75877363/125301163-a71f9900-e365-11eb-882a-022685f294a9.png">

2021-07-13 01:48 UTC, kst6294 reviewed
전체적으로 코드 확인해주세요 :)

2021-07-13 01:48 UTC, kst6294 commented on carts/views.py
> +                    Cart.objects.create(user_id=user.id, product_id=product.id)
get_or_create 메소드에 대해 알아보시면 좋겠습니다!

2021-07-13 01:48 UTC, kst6294 commented on carts/views.py
> +            product = Product.objects.get(id=data['productID'])
objects.get 메소드를 통해 product 를 호출할 때 실제 해당하는 모델이 없으면 model 에러가 발생하게 됩니다.
그에 해당하는 예외처리를 해주시면 좋겠습니다.  예외처가 되어 있다면 굳이 if 조건문을 작성하지 않아도 괜찮겠군요.

2021-07-13 01:48 UTC, kst6294 commented on carts/views.py
> +            if Cart.objects.filter(product_id=product, user_id=user).exists():
아 이미 장바구니에 있다는 메시지를 노출한다면, post에 해당하는 로직은 기존과 같이 진행해도 괜찮을 것 같습니다!

2021-07-13 01:48 UTC, kst6294 commented on carts/views.py
> +            if Cart.objects.filter(product=product, user=user).exists():
여기도 굳이 filtter().exists() 를 하지 않아도 괜찮을 것 같습니다.
해당하는 cart 는 하나만 존재하기 때문에 get 을 통해 해당하는 카트를 호출하고 바로 delete 하셔도 될 것 같습니다.
그렇다면 cart 가 없는 경우의 예외처리를 해주시면 되겠네요!

2021-07-13 03:54 UTC, Jacesoul commented on carts/views.py
> +                    Cart.objects.create(user_id=user.id, product_id=product.id)
get_or_create 메소드 공부하고 적용해보았습니다!

2021-07-13 03:54 UTC, Jacesoul commented on carts/views.py
> +            product = Product.objects.get(id=data['productID'])
model 에러에 해당하는 예외처리를 했습니다.

2021-07-13 03:55 UTC, Jacesoul commented on carts/views.py
> +            if Cart.objects.filter(product=product, user=user).exists():
filtter().exists() 를 사용하지 않고 get을 통해 구현을 해보았습니다.

2021-07-13 06:45 UTC, Jacesoul commented
수정 완료후 다시 push 했습니다!

2021-07-13 07:41 UTC, kst6294 requested changes
conflict 해결해주세요!

2021-07-13 08:17 UTC, Jacesoul commented
conflict 해결했습니다~!

2021-07-13 08:59 UTC, merged