결제후 주문내역 생성 기능 구현
wecode-bootcamp-korea/22-1st-Villy-backend pull request #13
Opened 2021-07-13 05:54 UTC by Jacesoul

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 결제후 주문내역 생성 기능 구현 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- 프런트에서 받은 product_id와 quantity로 total_price 값 생성
- 회원의 point 차감
- order 생성(새로운 uuid생성)
- point history 생성 
- order Item 생성
- Cart 내역 삭제 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 
- 깊게 주문에 대해 생각을 해보았지만 좀더 상세한 주문과정의 방법이 없을지 궁금합니다! 
- transaction rollback에 대해서도 공부를 하고 있는데 생각보다 간단히 데코레이션(@transaction.atomic)만 호출해주면 되는건지 궁금합니다! 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-13 07:44 UTC, kst6294 reviewed
요청, 응답에 대한 통신도 캡처해서 보여주세요.

2021-07-13 07:44 UTC, kst6294 commented on orders/views.py
> +            point        = user.point_set.get(id=1).point
id=1 은 무엇인가요?

2021-07-13 07:44 UTC, kst6294 commented on orders/views.py
> +            product_dict = data['products']
줄임말의 사용은 지양해주시고, 변수명은 그 의미를 쉽게 파악할 수 있게 해주세요.
변수명을 지정해주실 때 지우님은 이해하기 쉽지만, 리뷰를 하는 상대 혹은, 함께 작업하는 상대는 이해하기 어려울 수 있습니다.

2021-07-13 08:23 UTC, Jacesoul commented on orders/views.py
> +            point        = user.point_set.get(id=1).point
user=user 로 변경했습니다~!

2021-07-13 08:25 UTC, jacesoul commented on orders/views.py
> +            product_dict = data['products']
all_product_list로 변수 변경했습니다~!

2021-07-13 08:27 UTC, Jacesoul commented
<img width="1043" alt="스크린샷 2021-07-13 오후 5 26 54" src="https://user-images.githubusercontent.com/75877363/125418317-68aa687a-6ac5-4c57-81b2-1ab8ea17acf5.png">

2021-07-13 09:01 UTC, kst6294 requested changes
conflict 해결해주세요!

2021-07-14 01:22 UTC, kst6294 approved these changes

2021-07-14 01:22 UTC, kst6294 commented
Conflct 해결해주세요!

2021-07-14 01:47 UTC, Jacesoul commented
Conflct 해결하고 다시 push했습니다!

2021-07-14 06:15 UTC, merged